### ISSUE TITLE
Erro ao executar request

### ISSUE THREAD

**Issue by gustavo-silverio** [GGotardo/android-halley#1]
E/HttpClientObserver﹕ Error to make HTTP request
    java.lang.NullPointerException
            at com.halley.http.core.HalleyHttpResponse.<init>(HalleyHttpResponse.java:32)
            at com.halley.http.core.HalleyHttpAsyncRequest$1.call(HalleyHttpAsyncRequest.java:41)
            at com.halley.http.core.HalleyHttpAsyncRequest$1.call(HalleyHttpAsyncRequest.java:19)
            at rx.Observable$1.call(Observable.java:144)
            at rx.Observable$1.call(Observable.java:137)
            at rx.Observable$1.call(Observable.java:144)
            at rx.Observable$1.call(Observable.java:137)
            at rx.Observable.unsafeSubscribe(Observable.java:7600)
            at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:45)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)

**Comment by GGotardo** [comment]
Corrigido!
