### ISSUE TITLE
Erro requisitar imagem 

### ISSUE THREAD

**Issue by jvgengo** [GGotardo/android-halley#2]
03-20 11:05:24.833  25756-25756/br.com.meuevento E/HalleyHttpObserver﹕ Error while making HTTP request
    java.lang.NullPointerException: Attempt to invoke interface method 'org.apache.http.HttpEntity org.apache.http.HttpResponse.getEntity()' on a null object reference
            at com.halley.http.core.HalleyHttpResponse.<init>(HalleyHttpResponse.java:32)
            at com.halley.http.core.HalleyHttpAsyncRequest$1.call(HalleyHttpAsyncRequest.java:41)
            at com.halley.http.core.HalleyHttpAsyncRequest$1.call(HalleyHttpAsyncRequest.java:19)

**Comment by GGotardo** [comment]
Corrigido!
